name: Fly Deploy
on: [push]
env:
  F_HOST: ${{ secrets.F_HOST }}
  F_PORT: ${{ secrets.F_PORT }}
  F_USERNAME: ${{ secrets.F_USERNAME }}
  F_PASSWD: ${{ secrets.F_PASSWD }}
  F_DATABASE: ${{ secrets.F_DATABASE }}
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: |
          touch ./env/.config.env
          echo "F_HOST=$F_HOST\nF_PORT=$F_PORT\nF_USERNAME=$F_USERNAME\nF_PASSWD=$F_PASSWD\nF_DATABASE=$F_DATABASE" >> ./env/.config.env
  # create-env-file:
  #   name: Create env file
  #   runs-on: ubuntu-latest
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy

#name: Environment Variable - Secrets
#on: workflow_dispatch
#jobs:
#  secrets-test:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Access Secrets
#        run: |
#          echo "Secret Token : ${{ secrets.TEST_TOKEN }}"